LSTM_NUM_HIDDEN_LAYERS = 3

TRANSFORMER_NUM_HEADS = 4

HIDDEN_LAYER_SIZE = 64
SEQUENCES_MAX_LENGTH = 120
BATCH_SIZE = 32
NUM_EPOCHS = 20
LEARNING_RATE = 0.001
MODEL_DROPOUT_RATE = 0
VOCAB_MIN_FREQUENCY_TO_ADD = 2

DATA_TEST_SIZE = 0.2
TRAIN_TEST_SPLIT_RANDOM_STATE = 42
NUM_CPU_THREADS = 6

MODELS_ROOT_FOLDER = "trained_models"
DATASET_PATH = "skillss.csv"
MODEL_STATS_END_PATH = "stats.txt"
